### ISSUE TITLE
Feature request: Icons

### ISSUE THREAD

**Issue by luke-hill** [daveprowse/DrawOnYourScreen3#1]
Whilst the ctrl+f1 and ability to select different options is good. It would be good if one of these options yielded a graphic similar to MS Paint.

I've no idea how easy/hard this is to implement

P.S thanks for a great tool

**Comment by daveprowse** [comment]
Interesting. So I guess you are looking for something like this:
![Screenshot From 2024-11-22 10-40-07](https://github.com/user-attachments/assets/9e8dcfb0-88d8-4dd0-ab25-80f7cddccbf6)
That's an example from MS Paint. 

This sort of functionality could possibly be enabled via a shortcut/toggle. It could also be attached to, or separate from the right-click pop-up menu.

**Pros:** 
- Would allow for easier (and faster) mouse-based clicking of options.
- Would provide for better touchscreen usage.
- Would make the color palette and object selection more discernible at a single glance.

**Cons:**
- Goes against the core concept of being minimalistic (especially what's viewable on the display). Part of the goal of this extension is to be low profile and use very little resources. This idea would probably increase resource usage to a point that I wouldn't be comfortable with.
- Would indeed require a _lot_ of programming.
- Could easily break the system if not developed properly.

In the past, the previous developer had attempted a "touchscreen" variant of the program. That branch was quickly abandoned. I believe it was because the percentage of people using the extension on touchscreens was very small. Most people that use the extension have a configuration that consists of keyboard/mouse/drawing tablet.

Personally, I like the minimal approach -- that's what drew me to the program originally many years ago. 
When you start the extension, it indeed shows very little (and even that can be toggled off in the menu) which can be a bit of a learning curve for some users. However, once you memorize the shortcuts, the workflow becomes speedy and awesome. 
My usage is left-hand keyboard shortcuts and right hand stylus. I find this immensely preferable to programs that have clickable palettes.

However, I'll leave this feature request open for a week and see if anyone else chimes in.
I've also put it on the roadmap as a potential upgrade in the future, because it definitely could be accomplished side-by-side with the current workflow. 

Thanks for your input!
